# Generated by Django 3.2 on 2021-10-21 13:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_auto_20211019_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='photos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='pictures'),
        ),
    ]
